spring:
  application:
    name: Nurl

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/nurl}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    org.springframework.jdbc: INFO

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:900000}

app:
  base-url: ${APP_BASE_URL:http://localhost:8080}

  reserved-aliases:
    - login
    - register
    - links
    - health
    - admin
    - api
    - link
    - actuator
    - swagger

  cleanup:
    retention-days: ${CLEANUP_RETENTION_DAYS:30}
    cron: ${CLEANUP_CRON:0 0 2 * * *}