spring:
  application:
    name: Nurl

  datasource:
    url: jdbc:postgresql://localhost:5432/nurl
    username: postgres
    password: root

  jpa:
    show-sql: false

    hibernate:
      ddl-auto: none

    open-in-view: false

server:
  port: 8080

logging:
  level:
    org.springframework.jdbc: INFO