spring:
  application:
    name: Nurl

  datasource:
    url: jdbc:postgresql://localhost:5432/nurl
    username: postgres
    password: root

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update

    open-in-view: false

    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

server:
  port: 8080

logging:
  level:
    org.springframework.jdbc: INFO