CREATE TABLE users (
                       id UUID NOT NULL,
                       created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                       email VARCHAR(255) NOT NULL,
                       name VARCHAR(100) NOT NULL,
                       password VARCHAR(255) NOT NULL,

                       CONSTRAINT users_pkey
                           PRIMARY KEY (id),

                       CONSTRAINT uk_users_email
                           UNIQUE (email)
);

CREATE TABLE links (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                       click_count BIGINT NOT NULL,
                       created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                       deleted BOOLEAN NOT NULL,
                       deleted_at TIMESTAMP WITH TIME ZONE,
                       expires_at TIMESTAMP WITH TIME ZONE,
                       original_url TEXT NOT NULL,
                       short_code VARCHAR(10) NOT NULL,
                       updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                       user_id UUID NOT NULL,

                       CONSTRAINT links_pkey
                           PRIMARY KEY (id),

                       CONSTRAINT uk_links_short_code
                           UNIQUE (short_code),

                       CONSTRAINT fk_links_user
                           FOREIGN KEY (user_id)
                               REFERENCES users(id)
);