CREATE TABLE refresh_tokens (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                token_hash VARCHAR(64) NOT NULL UNIQUE,

                                user_id UUID NOT NULL,

                                expires_at TIMESTAMP WITH TIME ZONE NOT NULL,

                                created_at TIMESTAMP WITH TIME ZONE NOT NULL,

                                revoked_at TIMESTAMP WITH TIME ZONE,

                                CONSTRAINT fk_refresh_tokens_user
                                    FOREIGN KEY (user_id)
                                        REFERENCES users(id)
);

CREATE INDEX idx_refresh_tokens_user_id
    ON refresh_tokens(user_id);

CREATE INDEX idx_refresh_tokens_expires_at
    ON refresh_tokens(expires_at);